export interface Airport {
  code: string;
  name: string;
  city: string;
  country: string;
  timezone: string;
  lat: number;
  lng: number;
  aliases?: string[];
}

export const AIRPORTS: Airport[] = [
  // --- INDIA (DOMESTIC & INTERNATIONAL HUBS) ---
  {
    code: 'BLR',
    name: 'Kempegowda International Airport',
    city: 'Bengaluru',
    country: 'India',
    timezone: 'UTC+5:30',
    lat: 13.1986,
    lng: 77.7066,
    aliases: ['Bangalore', 'Bengaluru', 'Kempegowda', 'Karnataka'],
  },
  {
    code: 'BOM',
    name: 'Chhatrapati Shivaji Maharaj International Airport',
    city: 'Mumbai',
    country: 'India',
    timezone: 'UTC+5:30',
    lat: 19.0896,
    lng: 72.8656,
    aliases: ['Bombay', 'Mumbai', 'CSMIA', 'Sahar', 'Santa Cruz', 'Maharashtra'],
  },
  {
    code: 'DEL',
    name: 'Indira Gandhi International Airport',
    city: 'Delhi',
    country: 'India',
    timezone: 'UTC+5:30',
    lat: 28.5562,
    lng: 77.1000,
    aliases: ['New Delhi', 'Delhi', 'IGI', 'Indira Gandhi', 'NCR'],
  },
  {
    code: 'CCU',
    name: 'Netaji Subhash Chandra Bose International Airport',
    city: 'Kolkata',
    country: 'India',
    timezone: 'UTC+5:30',
    lat: 22.6547,
    lng: 88.4467,
    aliases: ['Calcutta', 'Kolkata', 'Dum Dum', 'West Bengal'],
  },
  {
    code: 'MAA',
    name: 'Chennai International Airport',
    city: 'Chennai',
    country: 'India',
    timezone: 'UTC+5:30',
    lat: 12.9941,
    lng: 80.1709,
    aliases: ['Madras', 'Chennai', 'Meenambakkam', 'Tamil Nadu'],
  },
  {
    code: 'HYD',
    name: 'Rajiv Gandhi International Airport',
    city: 'Hyderabad',
    country: 'India',
    timezone: 'UTC+5:30',
    lat: 17.2403,
    lng: 78.4294,
    aliases: ['Hyderabad', 'Shamshabad', 'RGIA', 'Telangana'],
  },
  {
    code: 'AMD',
    name: 'Sardar Vallabhbhai Patel International Airport',
    city: 'Ahmedabad',
    country: 'India',
    timezone: 'UTC+5:30',
    lat: 23.0772,
    lng: 72.6347,
    aliases: ['Ahmedabad', 'Amdavad', 'Gujarat'],
  },
  {
    code: 'COK',
    name: 'Cochin International Airport',
    city: 'Kochi',
    country: 'India',
    timezone: 'UTC+5:30',
    lat: 10.1556,
    lng: 76.3917,
    aliases: ['Cochin', 'Kochi', 'Nedumbassery', 'Kerala', 'Ernakulam'],
  },
  {
    code: 'GOI',
    name: 'Dabolim Airport',
    city: 'Goa',
    country: 'India',
    timezone: 'UTC+5:30',
    lat: 15.3808,
    lng: 73.8314,
    aliases: ['Goa', 'Dabolim', 'South Goa', 'Vasco'],
  },
  {
    code: 'GOX',
    name: 'Manohar International Airport',
    city: 'Goa',
    country: 'India',
    timezone: 'UTC+5:30',
    lat: 15.7686,
    lng: 73.8647,
    aliases: ['Goa', 'Mopa', 'North Goa', 'Manohar Parrikar'],
  },
  {
    code: 'PNQ',
    name: 'Pune Airport',
    city: 'Pune',
    country: 'India',
    timezone: 'UTC+5:30',
    lat: 18.5822,
    lng: 73.9197,
    aliases: ['Pune', 'Poona', 'Lohegaon', 'Maharashtra'],
  },
  {
    code: 'JAI',
    name: 'Jaipur International Airport',
    city: 'Jaipur',
    country: 'India',
    timezone: 'UTC+5:30',
    lat: 26.8242,
    lng: 75.8122,
    aliases: ['Jaipur', 'Pink City', 'Sanganer', 'Rajasthan'],
  },
  {
    code: 'LKO',
    name: 'Chaudhary Charan Singh International Airport',
    city: 'Lucknow',
    country: 'India',
    timezone: 'UTC+5:30',
    lat: 26.7606,
    lng: 80.8893,
    aliases: ['Lucknow', 'Amausi', 'Uttar Pradesh'],
  },
  {
    code: 'TRV',
    name: 'Thiruvananthapuram International Airport',
    city: 'Thiruvananthapuram',
    country: 'India',
    timezone: 'UTC+5:30',
    lat: 8.4821,
    lng: 76.9200,
    aliases: ['Trivandrum', 'Thiruvananthapuram', 'Kerala'],
  },
  {
    code: 'CCJ',
    name: 'Calicut International Airport',
    city: 'Kozhikode',
    country: 'India',
    timezone: 'UTC+5:30',
    lat: 11.1368,
    lng: 75.9553,
    aliases: ['Calicut', 'Kozhikode', 'Karipur', 'Kerala', 'Malappuram'],
  },
  {
    code: 'IXE',
    name: 'Mangalore International Airport',
    city: 'Mangaluru',
    country: 'India',
    timezone: 'UTC+5:30',
    lat: 12.9613,
    lng: 74.8901,
    aliases: ['Mangalore', 'Mangaluru', 'Bajpe', 'Karnataka'],
  },
  {
    code: 'CJB',
    name: 'Coimbatore International Airport',
    city: 'Coimbatore',
    country: 'India',
    timezone: 'UTC+5:30',
    lat: 11.0300,
    lng: 77.0434,
    aliases: ['Coimbatore', 'Peelamedu', 'Tamil Nadu'],
  },
  {
    code: 'ATQ',
    name: 'Sri Guru Ram Dass Jee International Airport',
    city: 'Amritsar',
    country: 'India',
    timezone: 'UTC+5:30',
    lat: 31.7096,
    lng: 74.7973,
    aliases: ['Amritsar', 'Raja Sansi', 'Golden Temple', 'Punjab'],
  },
  {
    code: 'IXC',
    name: 'Shaheed Bhagat Singh International Airport',
    city: 'Chandigarh',
    country: 'India',
    timezone: 'UTC+5:30',
    lat: 30.6735,
    lng: 76.7885,
    aliases: ['Chandigarh', 'Mohali', 'Panchkula', 'Punjab', 'Haryana'],
  },
  {
    code: 'VNS',
    name: 'Lal Bahadur Shastri International Airport',
    city: 'Varanasi',
    country: 'India',
    timezone: 'UTC+5:30',
    lat: 25.4524,
    lng: 82.8593,
    aliases: ['Varanasi', 'Banaras', 'Benares', 'Kashi', 'Babatpur', 'Uttar Pradesh'],
  },
  {
    code: 'PAT',
    name: 'Jayprakash Narayan Airport',
    city: 'Patna',
    country: 'India',
    timezone: 'UTC+5:30',
    lat: 25.5913,
    lng: 85.0880,
    aliases: ['Patna', 'Bihar'],
  },
  {
    code: 'BBI',
    name: 'Biju Patnaik International Airport',
    city: 'Bhubaneswar',
    country: 'India',
    timezone: 'UTC+5:30',
    lat: 20.2444,
    lng: 85.8178,
    aliases: ['Bhubaneswar', 'Bhubaneshwar', 'Odisha'],
  },
  {
    code: 'SXR',
    name: 'Sheikh ul-Alam International Airport',
    city: 'Srinagar',
    country: 'India',
    timezone: 'UTC+5:30',
    lat: 33.9871,
    lng: 74.7742,
    aliases: ['Srinagar', 'Kashmir', 'Budgam'],
  },
  {
    code: 'IXZ',
    name: 'Veer Savarkar International Airport',
    city: 'Port Blair',
    country: 'India',
    timezone: 'UTC+5:30',
    lat: 11.6410,
    lng: 92.7297,
    aliases: ['Port Blair', 'Andaman', 'Nicobar'],
  },
  {
    code: 'GAU',
    name: 'Lokpriya Gopinath Bordoloi International Airport',
    city: 'Guwahati',
    country: 'India',
    timezone: 'UTC+5:30',
    lat: 26.1061,
    lng: 91.5859,
    aliases: ['Guwahati', 'Borjhar', 'Assam'],
  },
  {
    code: 'IDR',
    name: 'Devi Ahilya Bai Holkar Airport',
    city: 'Indore',
    country: 'India',
    timezone: 'UTC+5:30',
    lat: 22.7217,
    lng: 75.8011,
    aliases: ['Indore', 'Madhya Pradesh'],
  },
  {
    code: 'NAG',
    name: 'Dr. Babasaheb Ambedkar International Airport',
    city: 'Nagpur',
    country: 'India',
    timezone: 'UTC+5:30',
    lat: 21.0922,
    lng: 79.0472,
    aliases: ['Nagpur', 'Sonegaon', 'Maharashtra'],
  },
  {
    code: 'VTZ',
    name: 'Visakhapatnam International Airport',
    city: 'Visakhapatnam',
    country: 'India',
    timezone: 'UTC+5:30',
    lat: 17.7212,
    lng: 83.2245,
    aliases: ['Visakhapatnam', 'Vizag', 'Andhra Pradesh'],
  },
  {
    code: 'UDR',
    name: 'Maharana Pratap Airport',
    city: 'Udaipur',
    country: 'India',
    timezone: 'UTC+5:30',
    lat: 24.6177,
    lng: 73.8961,
    aliases: ['Udaipur', 'Dabok', 'Rajasthan'],
  },
  {
    code: 'CNN',
    name: 'Kannur International Airport',
    city: 'Kannur',
    country: 'India',
    timezone: 'UTC+5:30',
    lat: 11.9186,
    lng: 75.5484,
    aliases: ['Kannur', 'Mattannur', 'Kerala'],
  },
  {
    code: 'TRZ',
    name: 'Tiruchirappalli International Airport',
    city: 'Tiruchirappalli',
    country: 'India',
    timezone: 'UTC+5:30',
    lat: 10.7654,
    lng: 78.7097,
    aliases: ['Tiruchirappalli', 'Trichy', 'Tamil Nadu'],
  },
  {
    code: 'IXM',
    name: 'Madurai Airport',
    city: 'Madurai',
    country: 'India',
    timezone: 'UTC+5:30',
    lat: 9.8345,
    lng: 78.0934,
    aliases: ['Madurai', 'Tamil Nadu'],
  },
  {
    code: 'IXB',
    name: 'Bagdogra Airport',
    city: 'Siliguri',
    country: 'India',
    timezone: 'UTC+5:30',
    lat: 26.6812,
    lng: 88.3286,
    aliases: ['Bagdogra', 'Siliguri', 'Darjeeling', 'West Bengal'],
  },

  // --- MIDDLE EAST & GCC (AL-SAFR CORE DESTINATIONS) ---
  {
    code: 'DXB',
    name: 'Dubai International Airport',
    city: 'Dubai',
    country: 'United Arab Emirates',
    timezone: 'UTC+4',
    lat: 25.2532,
    lng: 55.3657,
    aliases: ['Dubai', 'UAE', 'Emirates'],
  },
  {
    code: 'DWC',
    name: 'Al Maktoum International Airport',
    city: 'Dubai',
    country: 'United Arab Emirates',
    timezone: 'UTC+4',
    lat: 24.8960,
    lng: 55.1614,
    aliases: ['Dubai World Central', 'DWC', 'Dubai South'],
  },
  {
    code: 'AUH',
    name: 'Zayed International Airport',
    city: 'Abu Dhabi',
    country: 'United Arab Emirates',
    timezone: 'UTC+4',
    lat: 24.4330,
    lng: 54.6511,
    aliases: ['Abu Dhabi', 'Zayed', 'UAE'],
  },
  {
    code: 'SHJ',
    name: 'Sharjah International Airport',
    city: 'Sharjah',
    country: 'United Arab Emirates',
    timezone: 'UTC+4',
    lat: 25.3286,
    lng: 55.5172,
    aliases: ['Sharjah', 'UAE', 'Air Arabia'],
  },
  {
    code: 'DOH',
    name: 'Hamad International Airport',
    city: 'Doha',
    country: 'Qatar',
    timezone: 'UTC+3',
    lat: 25.2731,
    lng: 51.6081,
    aliases: ['Doha', 'Qatar', 'Hamad'],
  },
  {
    code: 'RUH',
    name: 'King Khalid International Airport',
    city: 'Riyadh',
    country: 'Saudi Arabia',
    timezone: 'UTC+3',
    lat: 24.9576,
    lng: 46.6988,
    aliases: ['Riyadh', 'Saudi Arabia', 'KSA', 'King Khalid'],
  },
  {
    code: 'JED',
    name: 'King Abdulaziz International Airport',
    city: 'Jeddah',
    country: 'Saudi Arabia',
    timezone: 'UTC+3',
    lat: 21.6796,
    lng: 39.1565,
    aliases: ['Jeddah', 'Jidda', 'Makkah', 'Mecca', 'Hajj', 'Umrah', 'KSA'],
  },
  {
    code: 'MED',
    name: 'Prince Mohammad bin Abdulaziz International Airport',
    city: 'Medina',
    country: 'Saudi Arabia',
    timezone: 'UTC+3',
    lat: 24.5534,
    lng: 39.7051,
    aliases: ['Medina', 'Madinah', 'Prince Mohammad', 'KSA', 'Umrah'],
  },
  {
    code: 'DMM',
    name: 'King Fahd International Airport',
    city: 'Dammam',
    country: 'Saudi Arabia',
    timezone: 'UTC+3',
    lat: 26.4712,
    lng: 49.7979,
    aliases: ['Dammam', 'Khobar', 'Dhahran', 'Eastern Province', 'KSA'],
  },
  {
    code: 'KWI',
    name: 'Kuwait International Airport',
    city: 'Kuwait City',
    country: 'Kuwait',
    timezone: 'UTC+3',
    lat: 29.2266,
    lng: 47.9789,
    aliases: ['Kuwait', 'Kuwait City'],
  },
  {
    code: 'BAH',
    name: 'Bahrain International Airport',
    city: 'Manama',
    country: 'Bahrain',
    timezone: 'UTC+3',
    lat: 26.2708,
    lng: 50.6336,
    aliases: ['Bahrain', 'Manama', 'Muharraq'],
  },
  {
    code: 'MCT',
    name: 'Muscat International Airport',
    city: 'Muscat',
    country: 'Oman',
    timezone: 'UTC+4',
    lat: 23.5933,
    lng: 58.2844,
    aliases: ['Muscat', 'Seeb', 'Oman'],
  },
  {
    code: 'SLL',
    name: 'Salalah Airport',
    city: 'Salalah',
    country: 'Oman',
    timezone: 'UTC+4',
    lat: 17.0387,
    lng: 54.0914,
    aliases: ['Salalah', 'Dhofar', 'Oman'],
  },
  {
    code: 'CAI',
    name: 'Cairo International Airport',
    city: 'Cairo',
    country: 'Egypt',
    timezone: 'UTC+2',
    lat: 30.1219,
    lng: 31.4056,
    aliases: ['Cairo', 'Egypt', 'Al Qahirah'],
  },
  {
    code: 'AMM',
    name: 'Queen Alia International Airport',
    city: 'Amman',
    country: 'Jordan',
    timezone: 'UTC+3',
    lat: 31.7226,
    lng: 35.9932,
    aliases: ['Amman', 'Jordan', 'Queen Alia'],
  },
  {
    code: 'BEY',
    name: 'Beirut-Rafic Hariri International Airport',
    city: 'Beirut',
    country: 'Lebanon',
    timezone: 'UTC+2',
    lat: 33.8209,
    lng: 35.4884,
    aliases: ['Beirut', 'Lebanon', 'Rafic Hariri'],
  },
  {
    code: 'IST',
    name: 'Istanbul Airport',
    city: 'Istanbul',
    country: 'Turkey',
    timezone: 'UTC+3',
    lat: 41.2753,
    lng: 28.7519,
    aliases: ['Istanbul', 'Turkey', 'Turkiye'],
  },
  {
    code: 'SAW',
    name: 'Sabiha Gokcen International Airport',
    city: 'Istanbul',
    country: 'Turkey',
    timezone: 'UTC+3',
    lat: 40.8986,
    lng: 29.3092,
    aliases: ['Istanbul Sabiha', 'Sabiha Gokcen', 'Istanbul Asian Side'],
  },

  // --- UNITED KINGDOM & EUROPE ---
  {
    code: 'LHR',
    name: 'London Heathrow Airport',
    city: 'London',
    country: 'United Kingdom',
    timezone: 'UTC+0',
    lat: 51.4700,
    lng: -0.4543,
    aliases: ['London', 'Heathrow', 'UK', 'England', 'Great Britain'],
  },
  {
    code: 'LGW',
    name: 'London Gatwick Airport',
    city: 'London',
    country: 'United Kingdom',
    timezone: 'UTC+0',
    lat: 51.1537,
    lng: -0.1821,
    aliases: ['London Gatwick', 'Gatwick', 'UK'],
  },
  {
    code: 'STN',
    name: 'London Stansted Airport',
    city: 'London',
    country: 'United Kingdom',
    timezone: 'UTC+0',
    lat: 51.8860,
    lng: 0.2389,
    aliases: ['London Stansted', 'Stansted', 'UK'],
  },
  {
    code: 'MAN',
    name: 'Manchester Airport',
    city: 'Manchester',
    country: 'United Kingdom',
    timezone: 'UTC+0',
    lat: 53.3537,
    lng: -2.2750,
    aliases: ['Manchester', 'Ringway', 'UK'],
  },
  {
    code: 'EDI',
    name: 'Edinburgh Airport',
    city: 'Edinburgh',
    country: 'United Kingdom',
    timezone: 'UTC+0',
    lat: 55.9500,
    lng: -3.3725,
    aliases: ['Edinburgh', 'Scotland', 'Turnhouse', 'UK'],
  },
  {
    code: 'CDG',
    name: 'Paris Charles de Gaulle Airport',
    city: 'Paris',
    country: 'France',
    timezone: 'UTC+1',
    lat: 49.0097,
    lng: 2.5479,
    aliases: ['Paris', 'Charles de Gaulle', 'Roissy', 'France'],
  },
  {
    code: 'ORY',
    name: 'Paris Orly Airport',
    city: 'Paris',
    country: 'France',
    timezone: 'UTC+1',
    lat: 48.7262,
    lng: 2.3652,
    aliases: ['Paris Orly', 'Orly', 'France'],
  },
  {
    code: 'FRA',
    name: 'Frankfurt Airport',
    city: 'Frankfurt',
    country: 'Germany',
    timezone: 'UTC+1',
    lat: 50.0379,
    lng: 8.5622,
    aliases: ['Frankfurt', 'Frankfurt am Main', 'Germany', 'Rhein-Main'],
  },
  {
    code: 'MUC',
    name: 'Munich Airport',
    city: 'Munich',
    country: 'Germany',
    timezone: 'UTC+1',
    lat: 48.3537,
    lng: 11.7860,
    aliases: ['Munich', 'München', 'Munchen', 'Germany', 'Franz Josef Strauss'],
  },
  {
    code: 'BER',
    name: 'Berlin Brandenburg Airport',
    city: 'Berlin',
    country: 'Germany',
    timezone: 'UTC+1',
    lat: 52.3667,
    lng: 13.5033,
    aliases: ['Berlin', 'Brandenburg', 'Willy Brandt', 'Germany'],
  },
  {
    code: 'AMS',
    name: 'Amsterdam Airport Schiphol',
    city: 'Amsterdam',
    country: 'Netherlands',
    timezone: 'UTC+1',
    lat: 52.3105,
    lng: 4.7683,
    aliases: ['Amsterdam', 'Schiphol', 'Netherlands', 'Holland'],
  },
  {
    code: 'ZRH',
    name: 'Zurich Airport',
    city: 'Zurich',
    country: 'Switzerland',
    timezone: 'UTC+1',
    lat: 47.4582,
    lng: 8.5555,
    aliases: ['Zurich', 'Zürich', 'Kloten', 'Switzerland'],
  },
  {
    code: 'GVA',
    name: 'Geneva Airport',
    city: 'Geneva',
    country: 'Switzerland',
    timezone: 'UTC+1',
    lat: 46.2370,
    lng: 6.1092,
    aliases: ['Geneva', 'Genf', 'Genève', 'Cointrin', 'Switzerland'],
  },
  {
    code: 'FCO',
    name: 'Leonardo da Vinci–Fiumicino Airport',
    city: 'Rome',
    country: 'Italy',
    timezone: 'UTC+1',
    lat: 41.8003,
    lng: 12.2389,
    aliases: ['Rome', 'Roma', 'Fiumicino', 'Italy'],
  },
  {
    code: 'MXP',
    name: 'Milan Malpensa Airport',
    city: 'Milan',
    country: 'Italy',
    timezone: 'UTC+1',
    lat: 45.6301,
    lng: 8.7255,
    aliases: ['Milan', 'Milano', 'Malpensa', 'Italy'],
  },
  {
    code: 'MAD',
    name: 'Adolfo Suárez Madrid–Barajas Airport',
    city: 'Madrid',
    country: 'Spain',
    timezone: 'UTC+1',
    lat: 40.4839,
    lng: -3.5680,
    aliases: ['Madrid', 'Barajas', 'Spain'],
  },
  {
    code: 'BCN',
    name: 'Josep Tarradellas Barcelona–El Prat Airport',
    city: 'Barcelona',
    country: 'Spain',
    timezone: 'UTC+1',
    lat: 41.2974,
    lng: 2.0833,
    aliases: ['Barcelona', 'El Prat', 'Catalonia', 'Spain'],
  },
  {
    code: 'VIE',
    name: 'Vienna International Airport',
    city: 'Vienna',
    country: 'Austria',
    timezone: 'UTC+1',
    lat: 48.1103,
    lng: 16.5697,
    aliases: ['Vienna', 'Wien', 'Schwechat', 'Austria'],
  },
  {
    code: 'BRU',
    name: 'Brussels Airport',
    city: 'Brussels',
    country: 'Belgium',
    timezone: 'UTC+1',
    lat: 50.9010,
    lng: 4.4856,
    aliases: ['Brussels', 'Zaventem', 'Belgium'],
  },
  {
    code: 'DUB',
    name: 'Dublin Airport',
    city: 'Dublin',
    country: 'Ireland',
    timezone: 'UTC+0',
    lat: 53.4264,
    lng: -6.2499,
    aliases: ['Dublin', 'Ireland'],
  },
  {
    code: 'CPH',
    name: 'Copenhagen Airport',
    city: 'Copenhagen',
    country: 'Denmark',
    timezone: 'UTC+1',
    lat: 55.6180,
    lng: 12.6508,
    aliases: ['Copenhagen', 'Kastrup', 'Denmark'],
  },
  {
    code: 'ARN',
    name: 'Stockholm Arlanda Airport',
    city: 'Stockholm',
    country: 'Sweden',
    timezone: 'UTC+1',
    lat: 59.6498,
    lng: 17.9238,
    aliases: ['Stockholm', 'Arlanda', 'Sweden'],
  },
  {
    code: 'OSL',
    name: 'Oslo Gardermoen Airport',
    city: 'Oslo',
    country: 'Norway',
    timezone: 'UTC+1',
    lat: 60.1975,
    lng: 11.1004,
    aliases: ['Oslo', 'Gardermoen', 'Norway'],
  },
  {
    code: 'HEL',
    name: 'Helsinki-Vantaa Airport',
    city: 'Helsinki',
    country: 'Finland',
    timezone: 'UTC+2',
    lat: 60.3172,
    lng: 24.9633,
    aliases: ['Helsinki', 'Vantaa', 'Finland'],
  },
  {
    code: 'LIS',
    name: 'Humberto Delgado Airport',
    city: 'Lisbon',
    country: 'Portugal',
    timezone: 'UTC+0',
    lat: 38.7756,
    lng: -9.1354,
    aliases: ['Lisbon', 'Lisboa', 'Portela', 'Portugal'],
  },
  {
    code: 'ATH',
    name: 'Athens International Airport',
    city: 'Athens',
    country: 'Greece',
    timezone: 'UTC+2',
    lat: 37.9356,
    lng: 23.9484,
    aliases: ['Athens', 'Eleftherios Venizelos', 'Greece'],
  },

  // --- ASIA-PACIFIC ---
  {
    code: 'SIN',
    name: 'Singapore Changi Airport',
    city: 'Singapore',
    country: 'Singapore',
    timezone: 'UTC+8',
    lat: 1.3644,
    lng: 103.9915,
    aliases: ['Singapore', 'Changi'],
  },
  {
    code: 'BKK',
    name: 'Suvarnabhumi Airport',
    city: 'Bangkok',
    country: 'Thailand',
    timezone: 'UTC+7',
    lat: 13.6900,
    lng: 100.7501,
    aliases: ['Bangkok', 'Suvarnabhumi', 'Thailand'],
  },
  {
    code: 'DMK',
    name: 'Don Mueang International Airport',
    city: 'Bangkok',
    country: 'Thailand',
    timezone: 'UTC+7',
    lat: 13.9126,
    lng: 100.6068,
    aliases: ['Bangkok Don Mueang', 'Don Mueang', 'Thailand'],
  },
  {
    code: 'HKT',
    name: 'Phuket International Airport',
    city: 'Phuket',
    country: 'Thailand',
    timezone: 'UTC+7',
    lat: 8.1132,
    lng: 98.3169,
    aliases: ['Phuket', 'Thailand'],
  },
  {
    code: 'KUL',
    name: 'Kuala Lumpur International Airport',
    city: 'Kuala Lumpur',
    country: 'Malaysia',
    timezone: 'UTC+8',
    lat: 2.7456,
    lng: 101.7099,
    aliases: ['Kuala Lumpur', 'KLIA', 'Sepang', 'Malaysia'],
  },
  {
    code: 'CGK',
    name: 'Soekarno–Hatta International Airport',
    city: 'Jakarta',
    country: 'Indonesia',
    timezone: 'UTC+7',
    lat: -6.1275,
    lng: 106.6537,
    aliases: ['Jakarta', 'Cengkareng', 'Indonesia'],
  },
  {
    code: 'DPS',
    name: 'I Gusti Ngurah Rai International Airport',
    city: 'Bali',
    country: 'Indonesia',
    timezone: 'UTC+8',
    lat: -8.7481,
    lng: 115.1672,
    aliases: ['Bali', 'Denpasar', 'Ngurah Rai', 'Indonesia'],
  },
  {
    code: 'MNL',
    name: 'Ninoy Aquino International Airport',
    city: 'Manila',
    country: 'Philippines',
    timezone: 'UTC+8',
    lat: 14.5086,
    lng: 121.0194,
    aliases: ['Manila', 'NAIA', 'Philippines'],
  },
  {
    code: 'HAN',
    name: 'Noi Bai International Airport',
    city: 'Hanoi',
    country: 'Vietnam',
    timezone: 'UTC+7',
    lat: 21.2212,
    lng: 105.8072,
    aliases: ['Hanoi', 'Noi Bai', 'Vietnam'],
  },
  {
    code: 'SGN',
    name: 'Tan Son Nhat International Airport',
    city: 'Ho Chi Minh City',
    country: 'Vietnam',
    timezone: 'UTC+7',
    lat: 10.8188,
    lng: 106.6519,
    aliases: ['Ho Chi Minh City', 'Saigon', 'Tan Son Nhat', 'Vietnam'],
  },
  {
    code: 'HND',
    name: 'Tokyo Haneda Airport',
    city: 'Tokyo',
    country: 'Japan',
    timezone: 'UTC+9',
    lat: 35.5494,
    lng: 139.7798,
    aliases: ['Tokyo', 'Haneda', 'Japan'],
  },
  {
    code: 'NRT',
    name: 'Narita International Airport',
    city: 'Tokyo',
    country: 'Japan',
    timezone: 'UTC+9',
    lat: 35.7720,
    lng: 140.3929,
    aliases: ['Tokyo Narita', 'Narita', 'Japan'],
  },
  {
    code: 'KIX',
    name: 'Kansai International Airport',
    city: 'Osaka',
    country: 'Japan',
    timezone: 'UTC+9',
    lat: 34.4320,
    lng: 135.2304,
    aliases: ['Osaka', 'Kansai', 'Japan'],
  },
  {
    code: 'ICN',
    name: 'Incheon International Airport',
    city: 'Seoul',
    country: 'South Korea',
    timezone: 'UTC+9',
    lat: 37.4602,
    lng: 126.4407,
    aliases: ['Seoul', 'Incheon', 'Korea'],
  },
  {
    code: 'HKG',
    name: 'Hong Kong International Airport',
    city: 'Hong Kong',
    country: 'Hong Kong',
    timezone: 'UTC+8',
    lat: 22.3080,
    lng: 113.9185,
    aliases: ['Hong Kong', 'Chek Lap Kok', 'HK'],
  },
  {
    code: 'TPE',
    name: 'Taiwan Taoyuan International Airport',
    city: 'Taipei',
    country: 'Taiwan',
    timezone: 'UTC+8',
    lat: 25.0797,
    lng: 121.2342,
    aliases: ['Taipei', 'Taoyuan', 'Taiwan'],
  },
  {
    code: 'PEK',
    name: 'Beijing Capital International Airport',
    city: 'Beijing',
    country: 'China',
    timezone: 'UTC+8',
    lat: 40.0799,
    lng: 116.6031,
    aliases: ['Beijing', 'Peking', 'Capital', 'China'],
  },
  {
    code: 'PKX',
    name: 'Beijing Daxing International Airport',
    city: 'Beijing',
    country: 'China',
    timezone: 'UTC+8',
    lat: 39.5098,
    lng: 116.4105,
    aliases: ['Beijing Daxing', 'Daxing', 'China'],
  },
  {
    code: 'PVG',
    name: 'Shanghai Pudong International Airport',
    city: 'Shanghai',
    country: 'China',
    timezone: 'UTC+8',
    lat: 31.1443,
    lng: 121.8083,
    aliases: ['Shanghai', 'Pudong', 'China'],
  },
  {
    code: 'CAN',
    name: 'Guangzhou Baiyun International Airport',
    city: 'Guangzhou',
    country: 'China',
    timezone: 'UTC+8',
    lat: 23.3924,
    lng: 113.2988,
    aliases: ['Guangzhou', 'Canton', 'Baiyun', 'China'],
  },
  {
    code: 'CMB',
    name: 'Bandaranaike International Airport',
    city: 'Colombo',
    country: 'Sri Lanka',
    timezone: 'UTC+5:30',
    lat: 7.1808,
    lng: 79.8841,
    aliases: ['Colombo', 'Katunayake', 'Sri Lanka'],
  },
  {
    code: 'MLE',
    name: 'Velana International Airport',
    city: 'Malé',
    country: 'Maldives',
    timezone: 'UTC+5',
    lat: 4.1918,
    lng: 73.5290,
    aliases: ['Male', 'Malé', 'Maldives', 'Velana', 'Hulhule'],
  },
  {
    code: 'DAC',
    name: 'Hazrat Shahjalal International Airport',
    city: 'Dhaka',
    country: 'Bangladesh',
    timezone: 'UTC+6',
    lat: 23.8433,
    lng: 90.4044,
    aliases: ['Dhaka', 'Dacca', 'Zia', 'Bangladesh'],
  },
  {
    code: 'KTM',
    name: 'Tribhuvan International Airport',
    city: 'Kathmandu',
    country: 'Nepal',
    timezone: 'UTC+5:45',
    lat: 27.6966,
    lng: 85.3591,
    aliases: ['Kathmandu', 'Nepal', 'Tribhuvan'],
  },
  {
    code: 'SYD',
    name: 'Sydney Kingsford Smith Airport',
    city: 'Sydney',
    country: 'Australia',
    timezone: 'UTC+10',
    lat: -33.9399,
    lng: 151.1753,
    aliases: ['Sydney', 'Kingsford Smith', 'Mascot', 'Australia'],
  },
  {
    code: 'MEL',
    name: 'Melbourne Airport',
    city: 'Melbourne',
    country: 'Australia',
    timezone: 'UTC+10',
    lat: -37.6690,
    lng: 144.8410,
    aliases: ['Melbourne', 'Tullamarine', 'Australia'],
  },
  {
    code: 'BNE',
    name: 'Brisbane Airport',
    city: 'Brisbane',
    country: 'Australia',
    timezone: 'UTC+10',
    lat: -27.3842,
    lng: 153.1175,
    aliases: ['Brisbane', 'Australia'],
  },
  {
    code: 'PER',
    name: 'Perth Airport',
    city: 'Perth',
    country: 'Australia',
    timezone: 'UTC+8',
    lat: -31.9403,
    lng: 115.9668,
    aliases: ['Perth', 'Australia'],
  },
  {
    code: 'AKL',
    name: 'Auckland Airport',
    city: 'Auckland',
    country: 'New Zealand',
    timezone: 'UTC+12',
    lat: -37.0082,
    lng: 174.7850,
    aliases: ['Auckland', 'Mangere', 'New Zealand'],
  },

  // --- AMERICAS & CARIBBEAN ---
  {
    code: 'JFK',
    name: 'John F. Kennedy International Airport',
    city: 'New York',
    country: 'United States',
    timezone: 'UTC-5',
    lat: 40.6413,
    lng: -73.7781,
    aliases: ['New York', 'NYC', 'JFK', 'Queens', 'Idlewild', 'USA'],
  },
  {
    code: 'EWR',
    name: 'Newark Liberty International Airport',
    city: 'New York / Newark',
    country: 'United States',
    timezone: 'UTC-5',
    lat: 40.6895,
    lng: -74.1745,
    aliases: ['New York', 'Newark', 'NYC', 'New Jersey', 'EWR', 'USA'],
  },
  {
    code: 'LGA',
    name: 'LaGuardia Airport',
    city: 'New York',
    country: 'United States',
    timezone: 'UTC-5',
    lat: 40.7769,
    lng: -73.8740,
    aliases: ['New York', 'LaGuardia', 'NYC', 'Queens', 'USA'],
  },
  {
    code: 'LAX',
    name: 'Los Angeles International Airport',
    city: 'Los Angeles',
    country: 'United States',
    timezone: 'UTC-8',
    lat: 33.9416,
    lng: -118.4085,
    aliases: ['Los Angeles', 'LA', 'California', 'SoCal', 'LAX', 'USA'],
  },
  {
    code: 'SFO',
    name: 'San Francisco International Airport',
    city: 'San Francisco',
    country: 'United States',
    timezone: 'UTC-8',
    lat: 37.6213,
    lng: -122.3790,
    aliases: ['San Francisco', 'SFO', 'Bay Area', 'California', 'Silicon Valley', 'USA'],
  },
  {
    code: 'ORD',
    name: "O'Hare International Airport",
    city: 'Chicago',
    country: 'United States',
    timezone: 'UTC-6',
    lat: 41.9742,
    lng: -87.9073,
    aliases: ['Chicago', "O'Hare", 'OHare', 'Illinois', 'ORD', 'USA'],
  },
  {
    code: 'ATL',
    name: 'Hartsfield-Jackson Atlanta International Airport',
    city: 'Atlanta',
    country: 'United States',
    timezone: 'UTC-5',
    lat: 33.6407,
    lng: -84.4277,
    aliases: ['Atlanta', 'Hartsfield', 'Georgia', 'ATL', 'USA'],
  },
  {
    code: 'DFW',
    name: 'Dallas/Fort Worth International Airport',
    city: 'Dallas',
    country: 'United States',
    timezone: 'UTC-6',
    lat: 32.8998,
    lng: -97.0403,
    aliases: ['Dallas', 'Fort Worth', 'DFW', 'Texas', 'USA'],
  },
  {
    code: 'MIA',
    name: 'Miami International Airport',
    city: 'Miami',
    country: 'United States',
    timezone: 'UTC-5',
    lat: 25.7959,
    lng: -80.2870,
    aliases: ['Miami', 'Florida', 'MIA', 'USA'],
  },
  {
    code: 'SEA',
    name: 'Seattle-Tacoma International Airport',
    city: 'Seattle',
    country: 'United States',
    timezone: 'UTC-8',
    lat: 47.4502,
    lng: -122.3088,
    aliases: ['Seattle', 'SeaTac', 'Tacoma', 'Washington', 'SEA', 'USA'],
  },
  {
    code: 'BOS',
    name: 'Logan International Airport',
    city: 'Boston',
    country: 'United States',
    timezone: 'UTC-5',
    lat: 42.3656,
    lng: -71.0096,
    aliases: ['Boston', 'Logan', 'Massachusetts', 'BOS', 'USA'],
  },
  {
    code: 'IAD',
    name: 'Washington Dulles International Airport',
    city: 'Washington, D.C.',
    country: 'United States',
    timezone: 'UTC-5',
    lat: 38.9531,
    lng: -77.4565,
    aliases: ['Washington DC', 'Washington', 'Dulles', 'DC', 'Virginia', 'IAD', 'USA'],
  },
  {
    code: 'IAH',
    name: 'George Bush Intercontinental Airport',
    city: 'Houston',
    country: 'United States',
    timezone: 'UTC-6',
    lat: 29.9902,
    lng: -95.3368,
    aliases: ['Houston', 'Bush', 'Texas', 'IAH', 'USA'],
  },
  {
    code: 'MCO',
    name: 'Orlando International Airport',
    city: 'Orlando',
    country: 'United States',
    timezone: 'UTC-5',
    lat: 28.4312,
    lng: -81.3081,
    aliases: ['Orlando', 'Disney', 'Florida', 'MCO', 'USA'],
  },
  {
    code: 'LAS',
    name: 'Harry Reid International Airport',
    city: 'Las Vegas',
    country: 'United States',
    timezone: 'UTC-8',
    lat: 36.0840,
    lng: -115.1537,
    aliases: ['Las Vegas', 'Vegas', 'McCarran', 'Nevada', 'LAS', 'USA'],
  },
  {
    code: 'YYZ',
    name: 'Toronto Pearson International Airport',
    city: 'Toronto',
    country: 'Canada',
    timezone: 'UTC-5',
    lat: 43.6777,
    lng: -79.6248,
    aliases: ['Toronto', 'Pearson', 'Ontario', 'Canada', 'YYZ'],
  },
  {
    code: 'YVR',
    name: 'Vancouver International Airport',
    city: 'Vancouver',
    country: 'Canada',
    timezone: 'UTC-8',
    lat: 49.1967,
    lng: -123.1815,
    aliases: ['Vancouver', 'British Columbia', 'Canada', 'YVR'],
  },
  {
    code: 'YUL',
    name: 'Montréal–Trudeau International Airport',
    city: 'Montreal',
    country: 'Canada',
    timezone: 'UTC-5',
    lat: 45.4657,
    lng: -73.7455,
    aliases: ['Montreal', 'Montréal', 'Trudeau', 'Dorval', 'Quebec', 'Canada', 'YUL'],
  },
  {
    code: 'MEX',
    name: 'Mexico City International Airport',
    city: 'Mexico City',
    country: 'Mexico',
    timezone: 'UTC-6',
    lat: 19.4361,
    lng: -99.0719,
    aliases: ['Mexico City', 'Benito Juárez', 'CDMX', 'Mexico'],
  },
  {
    code: 'KIN',
    name: 'Norman Manley International Airport',
    city: 'Kingston',
    country: 'Jamaica',
    timezone: 'UTC-5',
    lat: 17.9357,
    lng: -76.7875,
    aliases: ['Kingston', 'Jamaica', 'Norman Manley', 'Caribbean', 'Palisadoes'],
  },
  {
    code: 'MBJ',
    name: 'Sangster International Airport',
    city: 'Montego Bay',
    country: 'Jamaica',
    timezone: 'UTC-5',
    lat: 18.5037,
    lng: -77.9134,
    aliases: ['Montego Bay', 'Jamaica', 'Sangster', 'Caribbean'],
  },
  {
    code: 'GRU',
    name: 'São Paulo/Guarulhos International Airport',
    city: 'São Paulo',
    country: 'Brazil',
    timezone: 'UTC-3',
    lat: -23.4356,
    lng: -46.4731,
    aliases: ['Sao Paulo', 'São Paulo', 'Guarulhos', 'Cumbica', 'Brazil'],
  },
  {
    code: 'EZE',
    name: 'Ministro Pistarini International Airport',
    city: 'Buenos Aires',
    country: 'Argentina',
    timezone: 'UTC-3',
    lat: -34.8222,
    lng: -58.5358,
    aliases: ['Buenos Aires', 'Ezeiza', 'Argentina'],
  },
  {
    code: 'BOG',
    name: 'El Dorado International Airport',
    city: 'Bogotá',
    country: 'Colombia',
    timezone: 'UTC-5',
    lat: 4.7016,
    lng: -74.1469,
    aliases: ['Bogota', 'Bogotá', 'El Dorado', 'Colombia'],
  },

  // --- AFRICA ---
  {
    code: 'JNB',
    name: 'O.R. Tambo International Airport',
    city: 'Johannesburg',
    country: 'South Africa',
    timezone: 'UTC+2',
    lat: -26.1367,
    lng: 28.2411,
    aliases: ['Johannesburg', 'Joburg', 'O.R. Tambo', 'Jan Smuts', 'South Africa'],
  },
  {
    code: 'CPT',
    name: 'Cape Town International Airport',
    city: 'Cape Town',
    country: 'South Africa',
    timezone: 'UTC+2',
    lat: -33.9715,
    lng: 18.6021,
    aliases: ['Cape Town', 'Kaapstad', 'South Africa'],
  },
  {
    code: 'NBO',
    name: 'Jomo Kenyatta International Airport',
    city: 'Nairobi',
    country: 'Kenya',
    timezone: 'UTC+3',
    lat: -1.3192,
    lng: 36.9275,
    aliases: ['Nairobi', 'Jomo Kenyatta', 'Embakasi', 'Kenya'],
  },
  {
    code: 'ADD',
    name: 'Addis Ababa Bole International Airport',
    city: 'Addis Ababa',
    country: 'Ethiopia',
    timezone: 'UTC+3',
    lat: 8.9779,
    lng: 38.7993,
    aliases: ['Addis Ababa', 'Bole', 'Ethiopian Airlines', 'Ethiopia'],
  },
  {
    code: 'CMN',
    name: 'Mohammed V International Airport',
    city: 'Casablanca',
    country: 'Morocco',
    timezone: 'UTC+1',
    lat: 33.3675,
    lng: -7.5899,
    aliases: ['Casablanca', 'Mohammed V', 'Nouasseur', 'Morocco'],
  },
];

// Curated top hubs shown when query is empty or for quick selection
export const POPULAR_AIRPORTS: Airport[] = [
  AIRPORTS.find((a) => a.code === 'BLR')!,
  AIRPORTS.find((a) => a.code === 'BOM')!,
  AIRPORTS.find((a) => a.code === 'DEL')!,
  AIRPORTS.find((a) => a.code === 'DXB')!,
  AIRPORTS.find((a) => a.code === 'DOH')!,
  AIRPORTS.find((a) => a.code === 'RUH')!,
  AIRPORTS.find((a) => a.code === 'LHR')!,
  AIRPORTS.find((a) => a.code === 'JFK')!,
  AIRPORTS.find((a) => a.code === 'SIN')!,
  AIRPORTS.find((a) => a.code === 'HND')!,
  AIRPORTS.find((a) => a.code === 'CCU')!,
  AIRPORTS.find((a) => a.code === 'MAA')!,
].filter(Boolean);

/**
 * Intelligent ranked search over the comprehensive airports database.
 * Supports IATA code, city names, country, airport names, and common colloquial aliases.
 */
export function searchAirports(rawQuery: string, limit = 15): Airport[] {
  const query = rawQuery.trim().toLowerCase();
  if (!query) {
    return POPULAR_AIRPORTS.slice(0, limit);
  }

  const scored: { airport: Airport; score: number }[] = [];

  for (const airport of AIRPORTS) {
    const code = airport.code.toLowerCase();
    const city = airport.city.toLowerCase();
    const name = airport.name.toLowerCase();
    const country = airport.country.toLowerCase();
    const aliases = (airport.aliases || []).map((al) => al.toLowerCase());

    let score = 0;

    // 1. Exact IATA match (highest priority)
    if (code === query) {
      score += 1500;
    } else if (code.startsWith(query)) {
      score += 600;
    }

    // 2. Exact City match or exact Alias match
    if (city === query) {
      score += 1000;
    } else if (aliases.includes(query)) {
      score += 950;
    }

    // 3. City starts with query or Alias starts with query
    if (city.startsWith(query)) {
      score += 500;
    } else if (aliases.some((al) => al.startsWith(query))) {
      score += 450;
    }

    // 4. Airport Name starts with query
    if (name.startsWith(query)) {
      score += 350;
    }

    // 5. Substring matches
    if (city.includes(query) && !city.startsWith(query)) {
      score += 200;
    }
    if (aliases.some((al) => al.includes(query) && !al.startsWith(query))) {
      score += 180;
    }
    if (name.includes(query) && !name.startsWith(query)) {
      score += 120;
    }

    // 6. Country match
    if (country === query) {
      score += 100;
    } else if (country.startsWith(query)) {
      score += 80;
    } else if (country.includes(query)) {
      score += 40;
    }

    if (score > 0) {
      scored.push({ airport, score });
    }
  }

  scored.sort((a, b) => b.score - a.score);
  return scored.slice(0, limit).map((s) => s.airport);
}

/**
 * Resolves an airport by code, city name, or alias.
 * Always returns the best matching Airport object or null.
 */
export function findAirport(queryOrCode: string): Airport | null {
  if (!queryOrCode) return null;
  const clean = queryOrCode.trim();
  const lower = clean.toLowerCase();
  const upper = clean.toUpperCase();

  // 1. Exact IATA code match
  const exactCode = AIRPORTS.find((a) => a.code === upper);
  if (exactCode) return exactCode;

  // 2. Exact City match
  const exactCity = AIRPORTS.find((a) => a.city.toLowerCase() === lower);
  if (exactCity) return exactCity;

  // 3. Exact Alias match
  const exactAlias = AIRPORTS.find((a) =>
    a.aliases?.some((al) => al.toLowerCase() === lower)
  );
  if (exactAlias) return exactAlias;

  // 4. Fuzzy / top ranked match
  const results = searchAirports(clean, 1);
  return results.length > 0 ? results[0] : null;
}
